# Generated by Django 3.1.3 on 2021-02-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0002_line'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': 'Line', 'verbose_name_plural': 'Lines'},
        ),
        migrations.AddField(
            model_name='line',
            name='stations',
            field=models.ManyToManyField(to='metro.Station', verbose_name='stations'),
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
