# Generated by Django 3.1.3 on 2021-02-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(max_length=100, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Movie Name'),
        ),
    ]
